# Generated by Django 3.2.3 on 2021-09-07 07:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, null=True, verbose_name='Customer name')),
                ('father_name', models.CharField(max_length=200, null=True, verbose_name='Customer father name')),
                ('cast', models.CharField(blank=True, max_length=200, null=True)),
                ('address', models.CharField(max_length=200, null=True, verbose_name='Address')),
                ('phone', models.CharField(max_length=12, verbose_name='Phone number')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('photo_of_customer', models.ImageField(blank=True, upload_to='customer/customer_photo/%Y/%m/%d/')),
                ('customer_signature', models.ImageField(blank=True, upload_to='customer/customer_signature_photo/%Y/%m/%d/')),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, null=True)),
                ('Description', models.CharField(blank=True, max_length=200, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('Original_price', models.FloatField(null=True)),
                ('Installment_price', models.FloatField(null=True)),
                ('Monthly_installment', models.FloatField(null=True)),
                ('addvance_price', models.FloatField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('price', models.FloatField(null=True)),
                ('dealer_name', models.CharField(max_length=200, null=True)),
                ('tag', models.CharField(blank=True, choices=[('January', 'January'), ('February', 'February'), ('March', 'March'), ('April', 'April'), ('May', 'May'), ('June', 'June'), ('July', 'July'), ('August', 'August'), ('September', 'September'), ('October', 'October'), ('November', 'November'), ('December', 'December'), ('Advance', 'Advance')], max_length=200)),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Manager.customer')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Manager.products')),
                ('tags', models.ManyToManyField(blank=True, to='Manager.Tag')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('order_ID', models.IntegerField(unique=True, verbose_name='Order ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Manager.customer')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Manager.products')),
            ],
        ),
        migrations.CreateModel(
            name='Installment',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Promised', 'Promised'), ('Given', 'Given')], max_length=200, null=True)),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Manager.customer')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Manager.products')),
            ],
        ),
    ]
