# Generated by Django 3.2.3 on 2021-09-10 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Manager', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receipt',
            name='tag',
        ),
        migrations.RemoveField(
            model_name='receipt',
            name='tags',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
